### ISSUE TITLE
Add cent and it is NaN

### ISSUE THREAD

**Issue by MindrupTh** [yajo10/harbour-expenditure#2]
Hi. It is not possible to add euros and cents? Everutime when the price contains euro and cents the target prrice is NaN.

**Comment by yajo10** [comment]
Hey, thank you for creating a issue. I tried to reproduce the issue and was not really able to do so.

Could you please add some notes how to reproduce.

![photo_2_2023-11-25_18-33-51](https://github.com/yajo10/harbour-expenditure/assets/11422331/a3ae1a13-7e81-4550-a2f3-50c4193fbf1d)
![photo_1_2023-11-25_18-33-51](https://github.com/yajo10/harbour-expenditure/assets/11422331/8658756e-f723-4566-a209-a093003db6f1)

**Comment by yajo10** [comment]
@MindrupTh I could reproduce it. After entering a price with euros and cents the decimal delimiter will be `,` . That will cause the `NaN`. If you explicitly click anywhere else after adding the price than the delimiter will be transformed into `.`. Than it will work. I'll try to fix it anyhow. 

Thanks for reporting!
